_posts/2016-06-01-yet-another-progressive-webapp-post.md

I added a link too (in case folks are interested).

Correcting the iOS Add to Homescreen introduction.

---

Guest-Book.json

Hello there! I used Mavo to suggest the following edits:
Added my message
Preview my changes here: https://ada.is/guest-book/?Guest-Book-storage=https%3A%2F%2Fgithub.com%2Fstephenbe%2Fadaroseedwards.github.io%2FGuest-Book.json

Suggested edits to data

---

_posts/2018-04-16-help-someone-has-pointed-out-my-conference-has-diversity-issues.md

Adding new blog post: “Help! someone has pointed out my conference has diversity issues!

New Blog Post: “Help! someone has pointed out my conference has diversity issues!

---

_posts/2017-12-12-raindrops-on-roses-whiskers-on-kittens-declarative-web-apis-and-truly-serverless-web-endpoints.md

Adding new blog post: Raindrops on roses, whiskers on kittens, declarative web APIs and truly serverless web endpoints

New Blog Post: Raindrops on roses, whiskers on kittens, declarative web APIs and truly serverless web endpoints

---

_posts/2018-06-15-isomorphic-es-modules.md

Adding new blog post: Isomorphic ES Modules

New Blog Post: Isomorphic ES Modules

---

_posts/2019-05-13--web-workers-in-the-real-world.md

Adding new blog post: Web Workers in the Real World

New Blog Post: Web Workers in the Real World

---

_posts/2018-12-06--web-development-on-a-phone-updated-for-linux-on-dex.md

Adding new blog post: Web Development on a Phone. Updated for Linux on DeX.

New Blog Post: Web Development on a Phone. Updated for Linux on DeX.

---

_posts/2019-05-16--using-houdini-paint-api-to-render-a-3d-model.md

Adding new blog post: Using Houdini Paint API to Render a 3D Model

New Blog Post: Using Houdini Paint API to Render a 3D Model

---

_posts/2019-06-11--six-assumptions-which-could-break-your-website.md

Adding new blog post: Six assumptions which could break your website

New Blog Post: Six assumptions which could break your website

---

_posts/2019-06-28--using-basis-textures-in-threejs.md

Adding new blog post: Using Basis Textures in Three.js

New Blog Post: Using Basis Textures in Three.js

---

_posts/2020-02-11--generating-a-water-effect-part-1-svg-and-canvas.md

Adding new blog post: Generating a water effect, part 1. SVG and Canvas

New Blog Post: Generating a water effect, part 1. SVG and Canvas

---

_posts/2020-02-25--testing-your-websites-on-real-devices.md

Adding new blog post: Testing your websites on real devices

New Blog Post: Testing your websites on real devices

---

_posts/2020-03-11--horizontally-scrolling-panes-with-clean-html-and-modern-css.md

Adding new blog post: Horizontally Scrolling Panes with clean HTML and modern CSS

New Blog Post: Horizontally Scrolling Panes with clean HTML and modern CSS

---

_posts/2020-03-17--enhancing-multi-pane-single-page-web-apps-with-intersection-observer.md

Adding new blog post: Enhancing Multi Pane, Single Page Web Apps with Intersection Observer

New Blog Post: Enhancing Multi Pane, Single Page Web Apps with Intersection Observer

---

_posts/2020-03-23--building-a-menu-which-reveals-on-scroll.md

Adding new blog post: Building a menu which reveals on scroll.

New Blog Post: Building a menu which reveals on scroll.

---

_posts/2020-04-23--animating-dom-changes.md

Adding new blog post: Animating DOM Changes

New Blog Post: Animating DOM Changes

---

_posts/2020-05-18--using-vr-controllers-and-locomotion-in-threejs.md

Adding new blog post: Using VR controllers and locomotion in THREE.js

New Blog Post: Using VR controllers and locomotion in THREE.js

---

_posts/2020-08-03--using-node-modules-in-deno.md

Adding new blog post: Using node modules in Deno

New Blog Post: Using node modules in Deno

---

_posts/2020-07-27--making-a-useful-offline-page-for-your-web-app.md

Adding new blog post: Making a useful ‘offline’ page for your web app.

New Blog Post: Making a useful ‘offline’ page for your web app.

---

_posts/2020-08-04--ar-in-the-web-now-in-samsung-internet-stable.md

Adding new blog post: AR in the Web, now in Samsung Internet Stable

New Blog Post: AR in the Web, now in Samsung Internet Stable

---

_posts/2020-09-30--redeeming-push-notifications.md

Adding new blog post: Redeeming Push Notifications

New Blog Post: Redeeming Push Notifications

---

_posts/2020-08-25--improve-device-integration-for-your-web-app-in-just-a-few-minutes.md

Adding new blog post: Improve device integration for your Web App in just a few minutes

New Blog Post: Improve device integration for your Web App in just a few minutes

---

_posts/2020-10-06--html-and-templates--javascript-template-literals.md

Adding new blog post: HTML and Templates & JavaScript Template Literals

New Blog Post: HTML and Templates & JavaScript Template Literals

---

_posts/2020-10-19--audio-on-the-web-for-games-and-vr.md

Adding new blog post: Audio on the Web, for Games and VR!

New Blog Post: Audio on the Web, for Games and VR!

---

_posts/2020-03-02--generating-a-water-effect-part-2.md

Adding new blog post: Generating a water effect, part 2.

New Blog Post: Generating a water effect, part 2.
